frames: []

epochs: 100

# optimizer
lr-siam: 0.01
lr-autoenc: 0.001
decay : 0.00004
lr-power : 0.9
momentum: 0.9
gamma: 0.2

# batch
batch-size: 2
batch-norm: True

# dataloader
n-segments-test: 300
delta-segments-test: 0
n-segments-train: 700
delta-segments-train: 300
n-workers: 4
cuda: False

# network input size
in-shape: 600

n-frames-epoch: 100

# augmentation
aug-noise: 0.1
aug-blur: 1.
aug-gamma: 0.2
aug-flip-proba: 0.5
aug-some: 2
aug-scale: 0.8
aug-rotate: 11.25
aug-shear: 22.5

# sampling
n-edges: 100
